import pandas as pd
import pytest
from numpy import nan

from heart_disease.config import FEATURES, TARGET_COLUMN


@pytest.fixture
def sample_data() -> pd.DataFrame:
    df = {
        "age": [34, 54, 54, 66, 41, 56, 60, 64, 62, 54, 36, 45, 60, 56, 70],
        "trestbps": [
            130.0,
            125.0,
            120.0,
            120.0,
            104.0,
            132.0,
            125.0,
            nan,
            152.0,
            125.0,
            130.0,
            130.0,
            102.0,
            nan,
            140.0,
        ],
        "chol": [
            161.0,
            273.0,
            258.0,
            nan,
            nan,
            184.0,
            nan,
            244.0,
            153.0,
            216.0,
            209.0,
            219.0,
            318.0,
            nan,
            nan,
        ],
        "thalch": [
            190.0,
            152.0,
            147.0,
            120.0,
            111.0,
            105.0,
            110.0,
            nan,
            97.0,
            140.0,
            178.0,
            130.0,
            160.0,
            nan,
            157.0,
        ],
        "oldpeak": [
            nan,
            0.5,
            0.4,
            nan,
            nan,
            2.1,
            0.1,
            nan,
            1.6,
            nan,
            nan,
            1.0,
            nan,
            nan,
            2.0,
        ],
        "sex": [
            "Female",
            "Male",
            "Male",
            "Male",
            "Male",
            "Male",
            "Male",
            "Male",
            "Male",
            "Male",
            "Male",
            "Male",
            "Female",
            "Male",
            "Male",
        ],
        "cp": [
            "atypical angina",
            "non-anginal",
            "non-anginal",
            "non-anginal",
            "asymptomatic",
            "asymptomatic",
            "asymptomatic",
            "asymptomatic",
            "asymptomatic",
            "asymptomatic",
            "non-anginal",
            "asymptomatic",
            "non-anginal",
            "asymptomatic",
            "asymptomatic",
        ],
        "fbs": [
            False,
            False,
            False,
            False,
            False,
            False,
            nan,
            True,
            False,
            False,
            False,
            False,
            False,
            False,
            True,
        ],
        "restecg": [
            "normal",
            "lv hypertrophy",
            "lv hypertrophy",
            "st-t abnormality",
            "st-t abnormality",
            "lv hypertrophy",
            "normal",
            "st-t abnormality",
            "st-t abnormality",
            "normal",
            "normal",
            "st-t abnormality",
            "normal",
            "lv hypertrophy",
            "normal",
        ],
        "exang": [
            False,
            False,
            False,
            False,
            False,
            True,
            False,
            nan,
            True,
            False,
            False,
            True,
            False,
            nan,
            True,
        ],
        "slope": [
            nan,
            "downsloping",
            "flat",
            "upsloping",
            nan,
            "flat",
            "upsloping",
            nan,
            "upsloping",
            nan,
            nan,
            "flat",
            "upsloping",
            nan,
            "flat",
        ],
        "ca": [
            nan,
            1.0,
            0.0,
            nan,
            nan,
            1.0,
            2.0,
            nan,
            nan,
            nan,
            nan,
            nan,
            1.0,
            nan,
            nan,
        ],
        "thal": [
            nan,
            "normal",
            "reversable defect",
            nan,
            nan,
            "fixed defect",
            nan,
            nan,
            "reversable defect",
            nan,
            nan,
            nan,
            "normal",
            nan,
            "reversable defect",
        ],
        "target": [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
    }

    return pd.DataFrame(df)


@pytest.fixture
def sample_features(sample_data: pd.DataFrame) -> pd.DataFrame:
    return sample_data[FEATURES]


@pytest.fixture
def sample_target(sample_data: pd.DataFrame) -> pd.Series:
    return sample_data[TARGET_COLUMN]
